apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: NodePort               # NodePort instead of ClusterIP
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: # 9100 change if different              # Cluster internal port
      targetPort: # 9100 change if different         # Pod container port
      nodePort: # 31000 change if different         # External port for access
