apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: youtube
type: # keep secret type 
stringData:
  JWT_SECRET: # keep your jwt secret
  CLOUDINARY_API_KEY: # keep your cloudinary api key
  CLOUDINARY_API_SECRET: # keep your cloudinary secret
