apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: # Opaque change if different
stringData:
  admin-user: # keep your admin password
  admin-password: # keep yout admin password
