apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: # 3000 change if different
    nodePort: # 30300 change if different
  selector:
    app: grafana
