apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: youtube
type: # keep your secret type
stringData:
  MONGO_INITDB_ROOT_USERNAME: # keep your mongodb init root username
  MONGO_INITDB_ROOT_PASSWORD: # keep your mongodb init root password
