apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone-mongodb
  namespace: youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          ports:
            - containerPort: # keep port number
          envFrom:
            - secretRef:
                name: mongodb-secret
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
