apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-mongodb
  namespace: youtube
spec:
  selector:
    app: mongodb
  ports:
    - port: # keep your port number
      targetPort: # keep your port number
