apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager.monitoring.svc.cluster.local:9093' # ip exposed through kubernetes cluster
                - 'http://192.168.56.120:30903/' # ip exposed through node port

    rule_files:
      - /etc/prometheus/alert-rules.yaml

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          # keep according to your need
          - targets: ['192.168.56.120:31000', '192.168.56.111:31000']

      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            # keep according to your need
            #- http://youtube-backend.youtube:5004/api/health
            - http://youtube-frontend.youtube.svc.cluster.local # this is for use within the kubernetes cluster
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.56.120:31115 # exposed node port for blackbox

  alert-rules.yaml: |
    groups:
    - name: test-alerts
      rules:
      - alert: TestEmailAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "🚨 Test alert"
          description: "This is a test alert to verify email delivery"
