apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: # 9090 change if required, exposed within the cluster
    nodePort: # 30090 change if required to, exposed using nodeport outside of cluster
  selector:
    app: prometheus
